~/apps/tftp-go put $1:map.tison ../assets/map.tison
~/apps/tftp-go put $1:sample-png-image-100kb.png ../assets/sample-png-image-100kb.png
~/apps/tftp-go put $1:sample-png-image_1mb.png ../assets/sample-png-image_1mb.png
~/apps/tftp-go put $1:sample-png-image_20mb.png ../assets/sample-png-image_20mb.png
~/apps/tftp-go put $1:macbeth.txt ../assets/macbeth.txt
~/apps/tftp-go put $1:map.json ../assets/map.json
~/apps/tftp-go put $1:example.html ../assets/example.html
~/apps/tftp-go put $1:openwrt-23.05.0-ath79-generic-openmesh_om2p-hs-v1-initramfs-kernel.bin ../assets/openwrt-23.05.0-ath79-generic-openmesh_om2p-hs-v1-initramfs-kernel.bin
~/apps/tftp-go put $1:numbers.txt ../assets/numbers.txt
~/apps/tftp-go put $1:README.txt ../assets/README.txt